@startuml



participant 企业微信主页面 as main
participant 添加成员页面 as add_member
participant 通讯录页面 as contact
participant 添加部门页面 as add_department
autonumber

main->add_member:跳转到添加\n成员操作
add_member->add_member:添加成员操作,点击保存
add_member->contact:跳转到通讯录页面
contact->contact:检查是否成功\n添加成员


main->contact:跳转到通讯录页面
contact->add_member:跳转到添加\n成员页面
add_member->add_member:添加成员操作,点击保存
add_member->contact:跳转到通讯录页面
contact->contact:检查是否成功\n添加成员


main->contact:跳转到通讯录页面
contact->add_department:点击新增部门按钮
add_department->add_department:新增部门操作\n点击保存
add_department->contact:返回通讯录页面
contact->contact:检查是否成功\n添加部门





@enduml